name: Push to Remote
on:
  push:
    branches:
      - main
jobs:
  push_to_remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to Remote
        run: |
          git remote add cloud https://github.com/dinesh-adobe/cloudgita.git 
          git push cloud main
