name: Publish to Medium

"on":
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to public repository
        id: push_directory
        uses: git@github.com:dinesh-adobe/cloudgita.git@SHA256:rNU//MrUg0GNZmrpGxJvktDUdLhkRRIsmLPaGdYQa9k
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WORKFLOW_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-github-username: 'dinesh-adobe'
          destination-repository-name: 'cloudgita'
          user-email: dineshk@adobe.com
          commit-message: pushed from $GITHUB_REF
          target-branch: main
